(dp1
S'output'
p2
S"<type 'exceptions.TypeError'> redirect() got an unexpected keyword argument 'value'"
p3
sS'layer'
p4
S'/home/ria/Desktop/web2py/applications/simpleNN/controllers/pima1.py'
p5
sS'code'
p6
S'<code object <module> at 0x7fd7233fbbb0, file "/home/ria/Desktop/web2py/applications/simpleNN/controllers/pima1.py", line 3>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/ria/Desktop/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/ria/Desktop/web2py/applications/simpleNN/controllers/pima1.py", line 16, in <module>\n  File "/home/ria/Desktop/web2py/gluon/globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/ria/Desktop/web2py/applications/simpleNN/controllers/pima1.py", line 14, in result2\n    redirect(URL(\'result1\'), value=value, client_side=True)\nTypeError: redirect() got an unexpected keyword argument \'value\'\n'
p11
s.