(dp1
S'output'
p2
S"<type 'exceptions.AssertionError'> "
p3
sS'layer'
p4
S'/home/ria/Desktop/web2py/applications/simpleNN/controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 0x7fa506451a30, file "/home/ria/Desktop/web2py/applications/simpleNN/controllers/default.py", line 1>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/ria/Desktop/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/ria/Desktop/web2py/applications/simpleNN/controllers/default.py", line 69, in <module>\n  File "/home/ria/Desktop/web2py/gluon/globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/ria/Desktop/web2py/applications/simpleNN/controllers/default.py", line 34, in index\n    model.fit(Z, Q, epochs=150, batch_size=10)\n  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 965, in fit\n    validation_steps=validation_steps)\n  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1646, in fit\n    self._make_train_function()\n  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 977, in _make_train_function\n    **self._function_kwargs)\n  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 1236, in function\n    return Function(inputs, outputs, updates=updates, **kwargs)\n  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 1222, in __init__\n    **kwargs)\n  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function.py", line 317, in function\n    output_keys=output_keys)\n  File "/usr/local/lib/python2.7/dist-packages/theano/compile/pfunc.py", line 486, in pfunc\n    output_keys=output_keys)\n  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 1839, in orig_function\n    name=name)\n  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 1519, in __init__\n    optimizer_profile = optimizer(fgraph)\n  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 99, in __call__\n    return self.optimize(fgraph)\n  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 88, in optimize\n    ret = self.apply(fgraph, *args, **kwargs)\n  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 242, in apply\n    sub_prof = optimizer.optimize(fgraph)\n  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 88, in optimize\n    ret = self.apply(fgraph, *args, **kwargs)\n  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 2498, in apply\n    lopt_change = self.process_node(fgraph, node, lopt)\n  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 2067, in process_node\n    self.failure_callback(e, self, repl_pairs, lopt, node)\n  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 1918, in warn_inplace\n    return NavigatorOptimizer.warn(exc, nav, repl_pairs, local_opt, node)\n  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 1904, in warn\n    raise exc\nAssertionError\n'
p11
s.